### ISSUE TITLE
Latest version not published in PlatformIO

### ISSUE THREAD

**Issue by kmomberg** [arduino-libraries/NTPClient#158] opened 2021-12-01 13:48 UTC
In PlatformIO the latest version is still 3.1.0 instead of 3.2.0.
Seems like an authorized user should publish the new version so it can be handled properly.

![Code_9XsDAZAY5w](https://user-images.githubusercontent.com/12562540/144245653-11cdd06f-9884-4356-a38a-e4bc73ed2c04.png)

**Comment by per1234** [comment] 2021-12-01 13:50
Closing as duplicate of https://github.com/arduino-libraries/NTPClient/issues/152

Please request the PlatformIO library registry maintainers to update the NTPClient library registration to point to this metadata file: https://github.com/arduino-libraries/NTPClient/blob/master/library.properties

**Comment by kmomberg** [comment] 2021-12-03 10:27
Hi @per1234 

I contacted PlatformIO maintaners, and the problem is clear and in fact, easy to solve.

**The problem:** Current library release 3.2.0 contains two different manifests with different versions: 3.1.0 in `library.json` and 3.2.0 in `library.properties`. Current master branch is fine as it only contains one manifest with the right version.

**The fix:** update version in `library.properties` to 3.2.1 and tag a new release 3.2.1.

Here's the complete response from PIO:

> Thanks for contacting us.
>
> 1) We removed your library from the registry to avoid duplicates.
> 2) We can't process 3.2.0 release because it is broken from our perspective. It contains 2 manifests with different versions: https://github.com/arduino-libraries/NTPClient/tree/3.2.0
> 
> Could you ask here https://github.com/arduino-libraries/NTPClient/issues to bump 3.2.1 release?

**Comment by per1234** [comment] 2021-12-03 10:48
Thanks for the information @kmomberg! I was not aware of the details of how the PlatformIO library system worked when two manifest files are present.

I am not in the position to make a release, but I will reopen this issue so that we can effectively track the need to do so.

**Comment by per1234** [comment] 2022-04-09 17:59
I missed that we had this open issue to track the need for a release and reopened https://github.com/arduino-libraries/NTPClient/issues/152 when the discussion was revived over there. Since that one has the most recent activity, I'll close this one so that we can try to consolidate the discussion in one place.

Sorry for the issue ping pong.

**Closed by per1234** 2022-04-09 17:59 UTC
Labels: type: imperfection
