### ISSUE TITLE
Is there a reason why the 3.2.0 isn't available in PlatformIO?

### ISSUE THREAD

**Issue by FredM67** [arduino-libraries/NTPClient#152] opened 2021-09-19 19:49 UTC
In PlatformIO, I get only the 3.1.0 :-(

**Comment by per1234** [comment] 2021-09-19 20:25
Closing as duplicate of https://github.com/arduino-libraries/NTPClient/pull/78

Since history showed that maintaining duplicate metadata files is not feasible and PlatformIO has support for Arduino's `library.properties` metadata file, the superfluous `library.json` metadata file was removed from this repository (https://github.com/arduino-libraries/NTPClient/pull/121). Please request the PlatformIO library registry maintainers to update the NTPClient library registration to point to this metadata file: https://github.com/arduino-libraries/NTPClient/blob/master/library.properties

**Comment by ivankravets** [comment] 2022-04-09 16:22
@per1234 could we ask you to bump v3.2.1? The v3.2.0 tag is broken, there are multiple manifests with different "version" fields. See https://github.com/arduino-libraries/NTPClient/tree/3.2.0

[arduino-libraries/NTPClient](https://registry.platformio.org/libraries/arduino-libraries/NTPClient) in PlatformIO Registry still points to the 3.1.0.

**Comment by per1234** [comment] 2022-04-09 16:37
Hi @ivankravets. I'm not really in the role to make releases of this project, but I will reopen the issue since it seems it is distinct from https://github.com/arduino-libraries/NTPClient/pull/78 after all. That will allow us to more effectively track the issue.

**Comment by ivankravets** [comment] 2022-04-09 16:40
Thanks, @per1234 

The same issue with https://github.com/arduino-libraries/ArduinoHttpClient , the `library.json` manifest does not contain "version" field.

I agree with you, it makes sense to remove "library.json" files from the libraries from this org if you don't need advanced control over the library build process.

Who could help with this?

**Comment by per1234** [comment] 2022-04-09 17:12
>The same issue with https://github.com/arduino-libraries/ArduinoHttpClient , the library.json manifest does not contain "version" field.

Thanks for bringing that to our attention. I have submitted a PR to address the issue: https://github.com/arduino-libraries/ArduinoHttpClient/pull/133

>Who could help with this?

I have assigned the issue to @aentinger since I see they have been the most actively involved with the project recently.

**Comment by aentinger** [comment] 2022-04-25 04:56
I'm a bit confused here.

It sounds to me the best way forward would be to [drop this line](https://github.com/arduino-libraries/NTPClient/blob/master/library.properties#L2) and then make a new release, i.e. v3.2.1? Please note that we do not control what platform.io does or does not do 🤷 .

**Comment by per1234** [comment] 2022-04-25 05:12
@aentinger the problem was caused by this line:

https://github.com/arduino-libraries/NTPClient/blob/3.2.0/library.json#L21

```json
  "version": "3.1.0",
```

It was not updated before the creation of the 3.2.0 tag in this repository, which caused the 3.2.0 tag to be rejected by the PlatformIO library manager. So PlatformIO users only have access to the old version from the time of the 3.1.0 tag.

The problem has since been fixed by the removal of the improperly maintained `library.json` file in https://github.com/arduino-libraries/NTPClient/pull/121

But there has not been a tag since that fix was made, so the fix hasn't actually taken effect yet. That will only happen when a new release of the library is made:

1. Bump the `version` field in library.properties
1. Make a new tag or release.

>Please note that we do not control what platform.io does or does not do

PlatformIO supports the library.properties metadata file. So the only thing that needs to be done is for us to maintain the file as is required by the Arduino Library Manager and PlatformIO will be able to work with that no problem. The previous problem was caused by the presence of PlatformIO's preferred `library.json` file in the repository. If that file is present, then it is used, and so must be valid. A problem with the `library.json` will cause the library to be rejected by the PlatformIO library manager even if the `library.properties` file is perfect. But we don't need to worry about that at all now that the `library.json` file has been removed.

**Comment by aentinger** [comment] 2022-04-25 07:12
Thank you for the explanation :+1: The thing that got me confused was that I could not find the **library.json** file anymore, which from the messages I learned was the apparent offender. Will follow your suggestions :+1:

**Comment by aentinger** [comment] 2022-04-25 07:15
Should be fixed, see https://github.com/arduino-libraries/NTPClient/releases/tag/3.2.1 :bow:

**Comment by per1234** [comment] 2022-04-25 07:45
Thanks @aentinger!

**Closed by per1234** 2022-04-25 07:45 UTC
Labels: type: imperfection, topic: infrastructure

**Comment by ivankravets** [comment] 2022-04-25 08:16
Thanks for solving this issue! The library has been updated https://registry.platformio.org/libraries/arduino-libraries/NTPClient

Have a great work week!
